name: CI/CD Pipeline using SCP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy via SCP
      uses: appleboy/scp-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_ADDRESS }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script_stop: true
        source: "*" 
        target: "/var/www/html" 